services:
  android:
    image: cimg/android:2025.12-ndk
    command: "bash /volumes/script.sh"
    env_file:
      - .env
    volumes:
      - ./volumes:/volumes
      - ./.gradle:/home/circleci/.gradle
      - ./project:/home/circleci/project
